# Generated by Django 4.0.3 on 2022-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=200, verbose_name='Название поста')),
                ('post_info', models.TextField(verbose_name='Информация')),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
