# Generated by Django 4.0.3 on 2022-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title_post',
            field=models.CharField(max_length=500, verbose_name='Название поста'),
        ),
    ]
