# Generated by Django 4.0.3 on 2022-07-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_title_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title_post',
            field=models.CharField(max_length=200, verbose_name='Название поста'),
        ),
    ]
