# Generated by Django 4.0.3 on 2022-05-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.CharField(max_length=250, verbose_name='Описание проекта')),
                ('image', models.ImageField(upload_to='portfolio/images/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на проекта')),
            ],
        ),
    ]
