# Generated by Django 4.0.3 on 2022-08-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_project_shots_portfolioshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioshots',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Проекты'),
        ),
    ]
