# Generated by Django 4.0.3 on 2022-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_shots_portfolioshots_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioshots',
            name='image',
            field=models.ImageField(upload_to='portfolio_shots/images/', verbose_name='Изображение'),
        ),
    ]
